title: Conor Kingston
description: Professional Portfolio
baseUrl: ""
url: "https://conorkingston.com"
markdown: kramdown
theme: minima
collections:
  case_studies:
    output: true
    permalink: /case_studies/:year/:month/:day/:title
  posts:
    permalink: /blog/:year/:month/:day/:title
